sonar.projectKey=AdeleyeAdeyemi_e-commerce_63af9b69-9305-4177-91aa-f2ba039312d7
sonar.projectName=e-commerce
sonar.sources=.
sonar.exclusions=**/.git/**,**/venv/**,**/__pycache__/**,**/node_modules/**,**/tests/**
