- name: Setup and Deploy Flask App
  hosts: web
  become: yes

  tasks:
    - name: Install required system packages
      yum:
        name:
          - git
          - docker
          - python3
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clone GitHub repo
      git:
        repo: https://github.com/AdeleyeAdeyemi/e-commerce.git
        dest: /home/ec2-user/e-commerce

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user/e-commerce
