- name: Setup and Deploy Flask App
  hosts: all
  become: yes

  vars:
    jenkins_user: ec2-user
    jenkins_home: /home/ec2-user

  tasks:

    - name: Install required system packages
      ansible.builtin.yum:
        name:
          - git
          - docker
          - python3
          - conntrack
          - curl-minimal
          - tar
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      ansible.builtin.user:
        name: "{{ jenkins_user }}"
        groups: docker
        append: yes

    - name: Reset SSH connection after Docker group change
      ansible.builtin.meta: reset_connection

    - name: Clone GitHub repo
      ansible.builtin.git:
        repo: https://github.com/AdeleyeAdeyemi/e-commerce.git
        dest: /home/ec2-user/e-commerce
        version: main
        force: yes
      become: yes

    # Do not start Elasticsearch/Logstash/Kibana before Minikube.
    # They consume too much RAM and disk on this test instance.

    - name: Stop existing Docker Compose containers
      ansible.builtin.shell: |
        /usr/local/bin/docker-compose down --remove-orphans
      args:
        chdir: "{{ jenkins_home }}/e-commerce"
        executable: /bin/bash
      become: yes
      failed_when: false

    - name: Remove unused Docker resources
      ansible.builtin.shell: |
        docker system prune -af
      become: yes
      changed_when: false

    - name: Get latest kubectl version
      ansible.builtin.shell: |
        curl -L -s https://dl.k8s.io/release/stable.txt
      register: kubectl_version
      changed_when: false
      become: no
      environment:
        HOME: "{{ jenkins_home }}"

    - name: Ensure ~/bin directory exists
      ansible.builtin.file:
        path: "{{ jenkins_home }}/bin"
        state: directory
        mode: '0755'
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"

    - name: Download kubectl
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: "{{ jenkins_home }}/bin/kubectl"
        mode: '0755'
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
      become: yes

    - name: Install Minikube
      ansible.builtin.get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
        dest: "{{ jenkins_home }}/bin/minikube"
        mode: '0755'
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
      become: yes

    - name: Fix Minikube directory ownership
      ansible.builtin.file:
        path: "{{ jenkins_home }}/.minikube"
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        recurse: yes
      become: yes
      failed_when: false

    - name: Start Minikube as ec2-user
      ansible.builtin.shell: |
        {{ jenkins_home }}/bin/minikube start  --driver=docker
        --kubernetes-version=stable
      become: yes
      become_user: "{{ jenkins_user }}"
      environment:
        HOME: "{{ jenkins_home }}"
        PATH: "{{ jenkins_home }}/bin:/usr/local/bin:/usr/bin:/bin"
      args:
        executable: /bin/bash

    - name: Ensure ~/app/K8S directory exists
      ansible.builtin.file:
        path: "{{ jenkins_home }}/app/K8S"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: '0755'
      become: yes

    - name: Copy Kubernetes manifests from cloned repository
      ansible.builtin.shell: |
        cp -r "{{ jenkins_home }}/e-commerce/K8S/." \
              "{{ jenkins_home }}/app/K8S/"
      become: yes
      become_user: "{{ jenkins_user }}"

    - name: Create devops-tools namespace
      ansible.builtin.shell: |
        {{ jenkins_home }}/bin/kubectl create namespace devops-tools \
          --dry-run=client \
          -o yaml | {{ jenkins_home }}/bin/kubectl apply -f -
      become: yes
      become_user: "{{ jenkins_user }}"
      environment:
        HOME: "{{ jenkins_home }}"
        PATH: "{{ jenkins_home }}/bin:/usr/local/bin:/usr/bin:/bin"
        KUBECONFIG: "{{ jenkins_home }}/.kube/config"
      args:
        executable: /bin/bash

    - name: Apply K8S manifests
      ansible.builtin.shell: |
        {{ jenkins_home }}/bin/kubectl apply  -f {{ jenkins_home }}/app/K8S/
      become: yes
      become_user: "{{ jenkins_user }}"
      environment:
        HOME: "{{ jenkins_home }}"
        PATH: "{{ jenkins_home }}/bin:/usr/local/bin:/usr/bin:/bin"
        KUBECONFIG: "{{ jenkins_home }}/.kube/config"
      args:
        executable: /bin/bash

    - name: Verify Minikube nodes
      ansible.builtin.shell: |
        {{ jenkins_home }}/bin/kubectl get nodes
      become: yes
      become_user: "{{ jenkins_user }}"
      environment:
        HOME: "{{ jenkins_home }}"
        PATH: "{{ jenkins_home }}/bin:/usr/local/bin:/usr/bin:/bin"
        KUBECONFIG: "{{ jenkins_home }}/.kube/config"
      args:
        executable: /bin/bash






    














